import { Router, type IRouter } from "express";
import healthRouter from "./health";
import anthropicRouter from "./anthropic/index";
import openrouterRouter from "./openrouter";
import agentsRouter from "./agents";
import swarmRouter from "./swarm";
import memoryRouter from "./memory";
import workersRouter from "./workers";
import pluginsRouter from "./plugins";
import providersRouter from "./providers";
import securityRouter from "./security";
import federationRouter from "./federation";
import goapRouter from "./goap";
import mcpRouter from "./mcp";
import multiChatRouter from "./multi-chat";
import godmodeRouter from "./godmode";
import runRouter from "./run";
import filesRouter from "./files";
import authRouter from "./auth";
import projectsRouter from "./projects";
import systemRouter from "./system";
import dbGuiRouter from "./db-gui";
import ideAgentRouter from "./ide-agent";
import gitRouter from "./git";
import billingRouter from "./billing";
import projectToolsRouter from "./project-tools";
import geminiRouter from "./gemini";
import ultraplinianRouter from "./ultraplinian";
import jarvisRouter from "./jarvis";
import superAgentRouter from "./super-agent";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/anthropic", anthropicRouter);
router.use("/openrouter", openrouterRouter);
router.use("/agents", agentsRouter);
router.use("/swarm", swarmRouter);
router.use("/memory", memoryRouter);
router.use("/workers", workersRouter);
router.use("/plugins", pluginsRouter);
router.use("/providers", providersRouter);
router.use("/security", securityRouter);
router.use("/federation", federationRouter);
router.use("/goap", goapRouter);
router.use("/mcp", mcpRouter);
router.use("/multi-chat", multiChatRouter);
router.use("/godmode", godmodeRouter);
router.use("/run", runRouter);
router.use("/files", filesRouter);
router.use("/auth", authRouter);
router.use("/projects", projectsRouter);
router.use("/projects", gitRouter);
router.use("/projects", projectToolsRouter);
router.use("/billing", billingRouter);
router.use("/system", systemRouter);
router.use("/db-gui", dbGuiRouter);
router.use("/ide-agent", ideAgentRouter);
router.use("/gemini", geminiRouter);
router.use("/ultraplinian", ultraplinianRouter);
router.use("/jarvis", jarvisRouter);
router.use("/super-agent", superAgentRouter);

export default router;
